language: java
jdk:
  - openjdk8
services:
  - docker

env:
  global:
   - secure: "tkkBliF2tqx6ewaf3ioOqsqCN5YWoDtiPL4NXG0RGDKvVENYkYO9msf889LK164+SRDgd0cIvazY69+xp6WhYsNDHa0xZTE3As5fHsnMhC6VPcF8E+9sFWZPlaESWWpmmkdi9bndIXiXYe6EiF9D1goZKOZ1fpgOjtCPpooj4/1G5t03rqTmKEYi6KBwzyBkgsS6iMbdzPYb0anbBUghS9eHpP7b0hnJr1jk1adQj+e+ILLw014SMmLbmqMvcTolLCDiFzHk9x5X6cfvuMSmzy2gG76bd++hy8MmssFinhyvXrfR6LMi3cJoAoNkGzl1/7FT68Qf2O1wqR4zXz3uohmHe8zju0eaWatR31l96shPEeUp0ToNKqTHa1XoIboiXmqyXAmzAu3J1HE/OAHoxn5sXFHDs/lZ+C3nnOfI1oKUbufJ+Y4tOkq322hqXLncDe/yzYgaKBw4NDPO3kQb2YLUObYUbmUVumBoglWcaUozfx2ZScaAI9yCOJeVmaSA9a0Rc+gfgNaU/Swxi5apArGtLXjFKvq6kFM3gDWQB8akmDZKkLswH5xqeuF2Pr09CcKHLO0OcXhAzDcrVCZmApRNX4LiJNC6JmcL+ctc3UExgrGRh8GbkCNs5d5LZ8cl91WrnK0r8BGrGCNFg7ysH0GtyvBcJyNPA2YJ3cSz6+g="
   - secure: "vCWXMBDIz3Wfa6nGkICxs9HXbQyaXrISwdEG1TWnOYq5wOYWGzItesCyXkVmmCsMlyEciA6ZbPTZg7hqaG2nj8vScnMnY/kcV6YqhMg+Ii2wuOOgU97L3F2wwIa1YU1xXQ6Zly0OUZHXXdBeQUu1trsCkQfLx87lb/dV743pMjOXBCv4RFWc2z0RlsEqxFkMCdR0WgUIZOkb099B8t//c+HKkKe1Ovd2ZpuuVMWPEHl/nwdDNbH6oyhiIE15ERkyVmjongvvQLmIhm7qa5LS/YQk2upLuQN/QL2T3rOBgZm7+J78oI0KVCvtQByHs4bJ/NCv/0txxmNYHe6R17OqCwiOJrY/goyAjXMEXgMm6yWZ7kV8rsPaKn/eOeHPW4BYxCkyXUW+UJ9tQskBiw/JE5XYwXsC0NF4io56h5M0B2oVFagud5ZZevee3MucUHVD+ENUdw4Vv4l70wyFToZY+ikgpx8J4jDvegmWZR9U1jMy6Df+rui6kAt2r3vzmWpRNqMazC/F2qLgiHWAJyNm+jIr/Cp4YbH8AG52xkkvPZ0eEASGxXNASThaHCqFuKgB6xSc3TrOVF5SrGL33uTO2NuFF0b5T96PxTRGt07E8D74j7A1DufQ0AvZ/nQ5TfMQpyWmKMLewRHFr4yTi6lhrmM61aAlzfK4RIfQfsM39jU="
   - COMMIT=${TRAVIS_COMMIT::7}
   - IMAGE_NAME=tabletennistournament/match-management-server

before_install:
  - chmod +x mvnw
  - docker pull openjdk:8-jdk-alpine

script:
  - ./mvnw clean install -B

after_success:
  - export TAG=`if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$TRAVIS_BRANCH-$COMMIT"; fi`
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker build . -t $IMAGE_NAME:latest
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:latest
  - docker push $IMAGE_NAME:$TAG

cache:
  directories:
    - '$HOME/.m2/repository'
