language: java
jdk:
  - openjdk8
services:
  - docker
matrix:
  fast_finish: true

env:
  global:
   - secure: "tkkBliF2tqx6ewaf3ioOqsqCN5YWoDtiPL4NXG0RGDKvVENYkYO9msf889LK164+SRDgd0cIvazY69+xp6WhYsNDHa0xZTE3As5fHsnMhC6VPcF8E+9sFWZPlaESWWpmmkdi9bndIXiXYe6EiF9D1goZKOZ1fpgOjtCPpooj4/1G5t03rqTmKEYi6KBwzyBkgsS6iMbdzPYb0anbBUghS9eHpP7b0hnJr1jk1adQj+e+ILLw014SMmLbmqMvcTolLCDiFzHk9x5X6cfvuMSmzy2gG76bd++hy8MmssFinhyvXrfR6LMi3cJoAoNkGzl1/7FT68Qf2O1wqR4zXz3uohmHe8zju0eaWatR31l96shPEeUp0ToNKqTHa1XoIboiXmqyXAmzAu3J1HE/OAHoxn5sXFHDs/lZ+C3nnOfI1oKUbufJ+Y4tOkq322hqXLncDe/yzYgaKBw4NDPO3kQb2YLUObYUbmUVumBoglWcaUozfx2ZScaAI9yCOJeVmaSA9a0Rc+gfgNaU/Swxi5apArGtLXjFKvq6kFM3gDWQB8akmDZKkLswH5xqeuF2Pr09CcKHLO0OcXhAzDcrVCZmApRNX4LiJNC6JmcL+ctc3UExgrGRh8GbkCNs5d5LZ8cl91WrnK0r8BGrGCNFg7ysH0GtyvBcJyNPA2YJ3cSz6+g="
   - secure: "vCWXMBDIz3Wfa6nGkICxs9HXbQyaXrISwdEG1TWnOYq5wOYWGzItesCyXkVmmCsMlyEciA6ZbPTZg7hqaG2nj8vScnMnY/kcV6YqhMg+Ii2wuOOgU97L3F2wwIa1YU1xXQ6Zly0OUZHXXdBeQUu1trsCkQfLx87lb/dV743pMjOXBCv4RFWc2z0RlsEqxFkMCdR0WgUIZOkb099B8t//c+HKkKe1Ovd2ZpuuVMWPEHl/nwdDNbH6oyhiIE15ERkyVmjongvvQLmIhm7qa5LS/YQk2upLuQN/QL2T3rOBgZm7+J78oI0KVCvtQByHs4bJ/NCv/0txxmNYHe6R17OqCwiOJrY/goyAjXMEXgMm6yWZ7kV8rsPaKn/eOeHPW4BYxCkyXUW+UJ9tQskBiw/JE5XYwXsC0NF4io56h5M0B2oVFagud5ZZevee3MucUHVD+ENUdw4Vv4l70wyFToZY+ikgpx8J4jDvegmWZR9U1jMy6Df+rui6kAt2r3vzmWpRNqMazC/F2qLgiHWAJyNm+jIr/Cp4YbH8AG52xkkvPZ0eEASGxXNASThaHCqFuKgB6xSc3TrOVF5SrGL33uTO2NuFF0b5T96PxTRGt07E8D74j7A1DufQ0AvZ/nQ5TfMQpyWmKMLewRHFr4yTi6lhrmM61aAlzfK4RIfQfsM39jU="
   # CONFIG_REPOSITORY
   - secure: "OAVvGEoKEI20wtXSarDPrirMoMIEer3qErW9JlfEanT4Ggu4E5q/nDNzH6xNjDCM/b8JYbHQ+YOi4AAvgNoqMVt/Y69s230JI3P8xpe5xaTDXak3zhFsWSkqiNIzOZcD5dSpAXOvfn0x8sRKKj4AOMuZ9vF2pHVCSOs1jyX+8daze7bHNZApmWB4jn8OcPr/YGmZ9CcsyoFwVFbA/V3R6cK+8yDXv9vGn9BMPdVmcGKTEhSfpEXRYP4K7A00Rx4brcp0PHoYBAlj1IKv3SszSUtQXhDn3NMZ1+m5yKK1N4Yc253xDjupFVWXr5BehGyay+8ovgHKpCTTtOToVRp9RG+nM5H+57aVGzwarV/9HssOP+KTDagbezDcR2auPwv16OIWh2tPrfKJFlrM6doDPXdAy0vy1+uMht++iLG2MUWg5fXDi7QF6yyCqbuFECLMbqcteAeNn3l4If2MQjuETQueGSOt433Rut3XFGKvL+5RwTnWj+km3BR1L+JC7/GBXMs7vh7IIpIZoxzCEFjQ0JIDCJzSjYRaVDJWJgg9CZwnJcqXMLYVHGNvQRrgOEvZcNpE4q+9w07CBgRWqr+hDckloYYPDBYYTB5eXSBgrK+PUCyxOUxHtkQWDWAukg85VjaVRH/KF+XuOQDKnM4RQPE1f56oitRX+hkSakwHWBs="
   - APP_NAME=ttt-staging
   - COMMIT=${TRAVIS_COMMIT::7}
   - IMAGE_NAME=tabletennistournament/match-management-server

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean install -B
  - export TAG=$(if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$TRAVIS_BRANCH-$COMMIT"; fi | sed 's/\//-/')
  - docker build . -t $IMAGE_NAME:latest
  - if [ $TRAVIS_BRANCH == "master" ]; then docker tag $IMAGE_NAME:latest $IMAGE_NAME:master; fi
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker push $IMAGE_NAME:latest
  - if [ $TRAVIS_BRANCH == "master" ]; then docker push $IMAGE_NAME:master; fi
  - docker push $IMAGE_NAME:$TAG
  - docker run -e APP_NAME=$APP_NAME -e CONFIG_REPOSITORY=$CONFIG_REPOSITORY -e YAML_PATH="app.backend.image.tag" -e NEW_VALUE=$TAG -e GIT_BRANCH=$TRAVIS_BRANCH -e BRANCH_TEMPLATE=app-template tabletennistournament/gitops-deploy

cache:
  directories:
    - '$HOME/.m2/repository'
