# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: chmod +x mvnw
  displayName: 'Add permissions'
- script: ./mvnw clean install -B
  displayName: 'Run maven install'
- task: Docker@2
  inputs:
    containerRegistry: 'DockerRegistry'
    repository: 'match-management-server'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.SourceVersion)
      latest
#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
